### ISSUE TITLE
Add chapter on how to obtain the undocumented "client" scope

### ISSUE THREAD

**Issue by DavidVotrubec** [ErikKalkoken/slackApiDoc#49]
The whole process is described here https://medium.com/@andrewarrow/how-to-get-slack-api-tokens-with-client-scope-e311856ebe9

Basically it is simple, just 2 steps, but it took me considerable time to find this know-how

**Comment by ErikKalkoken** [comment]
Have you tried the obtain a legacy token, which is the standard way of getting a token for the client scope? I checked today and while officially "legacy" and "not  recommended" it still seams to work. 

Here is the link: https://api.slack.com/custom-integrations/legacy-tokens

**Comment by ErikKalkoken** [comment]
I do not see any need to add this "hack", since its way easier to just use a legacy token which apparently still works. I also removed this info from my answer on Stack Overflow about this API method, since its unnecessary. If you still feel its relevant I would appreciate if you would add your own answer to the question instead of editing the accepted answer.
