### ISSUE TITLE
How to use chat.command in a slack app using legacy token

### ISSUE THREAD

**Issue by Avinesh** [ErikKalkoken/slackApiDoc#62]
The legacy token which is created for a workspace is to be used only by user or can it be used by a slack app?

**Comment by ErikKalkoken** [comment]
Since the previous answer on the same topic apparently was not clear enough, here is a more detailed answer:

Legacy tokens are special tokens that always have all permissions and scopes incl. admin. In addition they give the unique `post` scope, which can not be attained with any other token type. Consequently it is not possible to create Slack apps with the `post` scope.

Since most undocumented API methods require the post scope they can only be used with legacy tokens. 

Therefore the only way to enable Slack apps to use legacy tokens is to add them manually, e.g. by adding them to a local configuration file / database of your Slack app or by setting an environment variable.
